version: "3.5"

services:
  telp:
    container_name: telp_backend
    #    image: backend_psn:v2
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
    restart: always
#    links:
#      - db
    build:
      context: .
      target: backend
    ports:
      - 8881:8881
    networks:
      - internal-network

  nginx_psn:
    container_name: nginx_telp
    #    image: nginx_psn:v
    restart: always
    build:
      context: .
      target: nginx-frontend
    ports:
      - 8882:8882
    links:
      - telp:telp
    networks:
      - internal-network

  db:
    image: telp_db
    container_name: telp_db
    ports:
      - 5433:5432
#      - 5433:15432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telptracker
#      POSTGRES_USER: db3u
#      POSTGRES_PASSWORD: wvhFR7pwYtxUz5j7
#      POSTGRES_DB: db3
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - internal-network

networks:
  internal-network:
